version: '3'

services:
  spring_mysql_docker_sample:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db

  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=spring_mysql_docker_sample
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./.docker/mysql_data:/var/lib/mysql