spring:
  datasource:
    url: jdbc:mysql://db:3306/spring_mysql_docker_sample
    username: root
    password:
    name: SpringMysqlDockerSampleDataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

    hikari:
      pool-name: SpringMysqlDockerSamplePool
      connection-test-query: select now()
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect